#!/bin/bash

/usr/bin/pgrep -x "tpm_server" &> /dev/null
if [[ $? -eq 0 ]]; then   
   echo "tpm_server is already running, stop it first with pkill -x tpm_server"
   exit 1
fi

export TPM_PORT=9998
export TCSD_TCP_DEVICE_PORT=${TPM_PORT}
export TPM_SERVER_NAME=localhost
export TPM_SERVER_PORT=${TPM_PORT}
export TPM_PATH=~/.tpm0/

mkdir -p ${TPM_PATH}

touch ${TPM_PATH}/tpm_server.log

echo "$(date) TPM Server Starting" >> ${TPM_PATH}/tpm_server.log 

tpm_server >> ${TPM_PATH}/tpm_server.log &

sleep 2

tpmbios

